In [2]:
import pandas as pd
import datetime
from google.colab import files
import os
import glob
from datetime import datetime

Data Source Instructions: bea.gov > tools > interactive data > regional data (gdp and personal income orange button) > "begin using the data" > Gross Domestic Product (GDP) by County and Metropolitan Area > Real GDP in chained dollars (CAGDP9) > Metropolitan Statistical Area > Select all MSAs in Colorado (tip: ctrl + f ', CO' to find all 7 MSAs, use ctrl + click to select all Colorado MSAs > Unit of measure: Levels > select all years > download csv

Quick link to download site: https://apps.bea.gov/regional/downloadzip.cfm

##Backup

In [3]:
GDP_backup = {
    "GDP by Metropolitan Statistical Area" : "https://data.colorado.gov/api/views/82s5-cpkk/rows.csv?accessType=DOWNLOAD",
}

In [7]:
def make_backup(dict_):
  for dataset,cim_link in dict_.items():
    data = pd.read_csv(cim_link)
    data.to_csv('/content/drive/MyDrive/Colab Notebooks/BEA datasets/Gross Domestic Product by Metropolitan Area/CIM_Backup' + f'/{dataset}_CIM_backup ' +  str(datetime.now().date())+ '.csv')

In [8]:
#make_backup(GDP_backup)

##Update

In [9]:
new_data = files.upload()
print(type(new_data))
for filename in new_data.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=filename, length=len(new_data[filename])))

Saving Table.csv to Table.csv
<class 'dict'>
User uploaded file "Table.csv" with length 61600 bytes

In [10]:
os.getcwd(), os.listdir()

('/content', ['.config', 'drive', 'Table.csv', 'sample_data'])

In [11]:
#to-do: make this grab only the correct csv by filtering for part of the expected name with str.contains() or .glob()
csv = glob.glob('*.csv')[0]
csv

'Table.csv'

In [17]:
Full_data = pd.read_csv(os.path.join(os.getcwd(), csv), skiprows = 3)
Full_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoFips      254 non-null    object
 1   GeoName      245 non-null    object
 2   LineCode     238 non-null    float64
 3   Description  245 non-null    object
 4   2001         238 non-null    object
 5   2002         238 non-null    object
 6   2003         238 non-null    object
 7   2004         238 non-null    object
 8   2005         238 non-null    object
 9   2006         238 non-null    object
 10  2007         238 non-null    object
 11  2008         238 non-null    object
 12  2009         238 non-null    object
 13  2010         238 non-null    object
 14  2011         238 non-null    object
 15  2012         238 non-null    object
 16  2013         238 non-null    object
 17  2014         238 non-null    object
 18  2015         238 non-null    object
 19  2016         238 non-null    object
 20  2017         238 non-null    object
 21  2018         238 non-null    object
 22  2019         238 non-null    object
 23  2020         238 non-null    object
 24  2021         238 non-null    object
dtypes: float64(1), object(24)
memory usage: 49.7+ KB

In [18]:
Full_data.head(10)

,GeoFips,GeoName,LineCode,Description,2001,2002,2003,2004,2005,2006,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,14500,"Boulder, CO (Metropolitan Statistical Area) *",1.0,All industry total,18076532,16864232,17119892,17608890,17995277,18492771,...,20898736,21534323,22180386,23061774,23746927,25116663,25875121,27671842,27024647,29154660
1,14500,"Boulder, CO (Metropolitan Statistical Area) *",2.0,Private industries,15682824,14508638,14765637,15278807,15652203,16192235,...,18645330,19291813,19882728,20653148,21205425,22491149,23243909,24981011,24352408,26521975
2,14500,"Boulder, CO (Metropolitan Statistical Area) *",3.0,"Agriculture, forestry, fishing and hunting",7190,6635,2977,10357,3728,8644,...,6725,10455,6810,14561,10098,12513,11974,8516,11055,6081
3,14500,"Boulder, CO (Metropolitan Statistical Area) *",6.0,"Mining, quarrying, and oil and gas extraction",57150,60521,79844,100546,165626,183534,...,57004,54737,69400,72559,53521,39062,36898,46757,47004,55751
4,14500,"Boulder, CO (Metropolitan Statistical Area) *",10.0,Utilities,98176,93941,113704,123392,117761,123285,...,87384,86149,92637,98577,85617,48146,36329,64705,87754,78378
5,14500,"Boulder, CO (Metropolitan Statistical Area) *",11.0,Construction,1049081,890082,830041,755026,663929,603513,...,367190,420607,478109,539612,629031,661326,688689,689064,607664,588646
6,14500,"Boulder, CO (Metropolitan Statistical Area) *",12.0,Manufacturing,1514332,1597463,1692414,1937259,2079706,2301230,...,2680869,2971848,3270661,3455414,3346866,3484526,3726752,3430246,3474748,3819110
7,14500,"Boulder, CO (Metropolitan Statistical Area) *",13.0,Durable goods manufacturing,(D),920938,(D),(D),(D),(D),...,1839586,2269352,2525350,2689037,2652897,2926538,3128051,2746083,2648708,2813743
8,14500,"Boulder, CO (Metropolitan Statistical Area) *",25.0,Nondurable goods manufacturing,(D),756378,(D),(D),(D),(D),...,841283,705028,749309,772470,706230,596141,639204,699804,819029,978419
9,14500,"Boulder, CO (Metropolitan Statistical Area) *",34.0,Wholesale trade,788672,705046,736107,790565,857623,962034,...,1093614,1075503,1039658,1014510,1015971,1044822,1126299,1123016,1115529,1202651

Target MSAs:

Denver-Aurora-Lakewood, CO (Metropolitan Statistical Area) *   
Boulder, CO (Metropolitan Statistical Area) *                   
Greeley, CO (Metropolitan Statistical Area) *                   
Pueblo, CO (Metropolitan Statistical Area)                      
Colorado Springs, CO (Metropolitan Statistical Area)            
Grand Junction, CO (Metropolitan Statistical Area)              
Fort Collins, CO (Metropolitan Statistical Area)                

Name: GeoName, dtype: int64

## Removing footers and fluff

In [19]:
df = Full_data[Full_data['GeoName'].notna()].copy()
df.GeoName.value_counts()
#35 statistics per MSA

Boulder, CO (Metropolitan Statistical Area) *                   35
Colorado Springs, CO (Metropolitan Statistical Area)            35
Denver-Aurora-Lakewood, CO (Metropolitan Statistical Area) *    35
Fort Collins, CO (Metropolitan Statistical Area)                35
Grand Junction, CO (Metropolitan Statistical Area)              35
Greeley, CO (Metropolitan Statistical Area) *                   35
Pueblo, CO (Metropolitan Statistical Area)                      35
Name: GeoName, dtype: int64

In [20]:
df.query('Description == "Addenda:"').head(3)

,GeoFips,GeoName,LineCode,Description,2001,2002,2003,2004,2005,2006,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
28,14500,"Boulder, CO (Metropolitan Statistical Area) *",NaN,Addenda:,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,17820,"Colorado Springs, CO (Metropolitan Statistical...",NaN,Addenda:,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,19740,"Denver-Aurora-Lakewood, CO (Metropolitan Stati...",NaN,Addenda:,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##Transforms

In [21]:
df.drop(columns = ['LineCode'], inplace = True)

In [22]:
#testing there are 34 industries.
df = df[df.Description != 'Addenda:'].copy()
assert df.Description.nunique() == 34, 'There are more industries than expected'

In [23]:
#testing years column start hasn't shifted.
years = df.columns[3:]
try:
  [int(year) for year in years]
except:
  raise AssertionError ('Something is wrong with the years')

In [24]:
#melting years columns into one with static GeoFips, Geoname, Description columns
final_df = df.melt(id_vars = ['GeoFips', 'GeoName', 'Description'], value_vars = years, var_name = 'Year', value_name = 'Thousands_dollars')
#Sort by Geofips, then Description, then year.
final_df.sort_values(['GeoFips', 'Description', 'Year'])

,GeoFips,GeoName,Description,Year,Thousands_dollars
25,14500,"Boulder, CO (Metropolitan Statistical Area) *",Accommodation and food services,2001,566968
263,14500,"Boulder, CO (Metropolitan Statistical Area) *",Accommodation and food services,2002,494797
501,14500,"Boulder, CO (Metropolitan Statistical Area) *",Accommodation and food services,2003,475729
739,14500,"Boulder, CO (Metropolitan Statistical Area) *",Accommodation and food services,2004,486778
977,14500,"Boulder, CO (Metropolitan Statistical Area) *",Accommodation and food services,2005,516702
...,...,...,...,...,...
4042,39380,"Pueblo, CO (Metropolitan Statistical Area)",Transportation and utilities,2017,717389
4280,39380,"Pueblo, CO (Metropolitan Statistical Area)",Transportation and utilities,2018,726534
4518,39380,"Pueblo, CO (Metropolitan Statistical Area)",Transportation and utilities,2019,684292
4756,39380,"Pueblo, CO (Metropolitan Statistical Area)",Transportation and utilities,2020,(D)
4994,39380,"Pueblo, CO (Metropolitan Statistical Area)",Transportation and utilities,2021,732307

In [25]:
#Breaking the '(D)' values into their own column and leaving a '' in its place

Blank_Key = pd.Series(data = ['' for row in final_df.Thousands_dollars], name = 'Blank_Key')
Thousands_dollars = final_df.Thousands_dollars.copy()
for id, entry in enumerate(final_df.Thousands_dollars):
  try:
    int(entry)
    Blank_Key.iloc[id] = ''
    Thousands_dollars.iloc[id] = entry
  except:
    Blank_Key.iloc[id] = entry
    Thousands_dollars.iloc[id] = ''

In [26]:
final_df['Thousands_dollars'] = Thousands_dollars
final_df['Blank_Key'] = Blank_Key

In [ ]:
#cleaner if desired.
#final_df = filtered(final_df)

###Renaming columns

In [27]:
final_df.rename(columns = {'GeoName' : 'msa_name', 'Description':'Industry'}, inplace = True )

###Cleaning msa name to match CIM format:

In [28]:
final_df['msa_name'] =  final_df.msa_name.apply(lambda x: x.replace(' (Metropolitan Statistical Area)', ''))
final_df['msa_name'] = final_df.msa_name.apply(lambda x: x.replace(' *', ''))

### Sanity Check

In [29]:
#Sanity Check
final_df

,GeoFips,msa_name,Industry,Year,Thousands_dollars,Blank_Key
0,14500,"Boulder, CO",All industry total,2001,18076532,
1,14500,"Boulder, CO",Private industries,2001,15682824,
2,14500,"Boulder, CO","Agriculture, forestry, fishing and hunting",2001,7190,
3,14500,"Boulder, CO","Mining, quarrying, and oil and gas extraction",2001,57150,
4,14500,"Boulder, CO",Utilities,2001,98176,
...,...,...,...,...,...,...
4993,39380,"Pueblo, CO",Trade,2021,682453,
4994,39380,"Pueblo, CO",Transportation and utilities,2021,732307,
4995,39380,"Pueblo, CO",Manufacturing and information,2021,768829,
4996,39380,"Pueblo, CO",Private goods-producing industries 2/,2021,993064,
4997,39380,"Pueblo, CO",Private services-providing industries 3/,2021,4161292,

##Export

In [30]:
#Consider adding auto-thisdir-creation for easy transfer to other drive environments.
#Colorado_GDPbyMSA.to_csv('/content/drive/MyDrive/Colab Notebooks/BEA datasets/GDP New dataset for CIM/' +str(datetime.now().date()) + ' GDP by Metropolitan Statistical Area for CIM.csv')
final_df.to_csv('Updated_GDP_MSA.csv', index = False)
files.download('Updated_GDP_MSA.csv')