In [ ]:
import pandas as pd
import numpy as np
import glob
import os 
import datetime
from google.colab import files

Navigate to https://apps.bea.gov/regional/downloadzip.cfm and download Personal Consumption Expenditures by State. Open the zipped file and select All Areas. Replace the dataset on CIM with the resulting file.

### Asserting Folder Structure exists.

In [ ]:
#fill notebook_folder_path to this notebook's path on drive.

notebook_folder_path = '/content/drive/MyDrive/Colab Notebooks/BEA datasets/Personal Consumption Expenditures by State (SAEXP1)'

dataset_CIM_name = 'Personal Consumption Expenditures'

Folder_names = ['CIM_Backup']

#Create folders where this notebook lives if they dont exist
for folder_name in Folder_names:
  if not os.path.exists(notebook_folder_path + f'/{folder_name}'):
    os.mkdir(notebook_folder_path + f'/{folder_name}')

##Backing up dataset

In [ ]:
backup = {
    "Personal Consumption Expenditures" : "https://data.colorado.gov/api/views/n55r-9hud/rows.csv?accessType=DOWNLOAD"
}

In [ ]:
def make_backup(dict_):
  for dataset,cim_link in dict_.items():
    data = pd.read_csv(cim_link)
    data.to_csv(notebook_folder_path + '/CIM_Backup' + f'/{dataset}_CIM_Backup ' +  str(datetime.datetime.now().date()))

In [ ]:

make_backup(backup)

##Update

In [ ]:
new_data = files.upload()
print(type(new_data))
for filename in new_data.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=filename, length=len(new_data[filename])))

Saving SAPCE1__ALL_AREAS_1997_2021.csv to SAPCE1__ALL_AREAS_1997_2021.csv
<class 'dict'>
User uploaded file "SAPCE1__ALL_AREAS_1997_2021.csv" with length 428556 bytes

In [ ]:
csv = glob.glob('*.csv')[0]
csv

'SAPCE1__ALL_AREAS_1997_2021.csv'

In [ ]:
Full_data = pd.read_csv(os.path.join(os.getcwd(), csv))

#As long as geofips remains constant, data size sholdnt be over 1440 rows w/o footers/headers.
#removing footers
Full_data

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1997,1998,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,"""00000""",United States,,SAPCE1,1.0,...,Personal consumption expenditures,Millions of current dollars,5536790.1,5877248.2,...,11047363.2,11363527.8,11847725.1,12263476.3,12693265.6,13233608.6,13904979.5,14392721.0,14116165.7,15902575.3
1,"""00000""",United States,,SAPCE1,2.0,...,Goods,Millions of current dollars,2006505.5,2108439.4,...,3637739.2,3729972.7,3862956.5,3922992.5,3991848.9,4159375.0,4355177.3,4473509.9,4670135.0,5496516.0
2,"""00000""",United States,,SAPCE1,3.0,...,Durable goods,Millions of current dollars,715529.6,779293.4,...,1144221.0,1189413.3,1242075.5,1307605.2,1345193.9,1398248.0,1470686.8,1510542.9,1646793.0,2060246.3
3,"""00000""",United States,,SAPCE1,4.0,...,Motor vehicles and parts,Millions of current dollars,293082.5,320204.7,...,396607.9,417533.0,441992.0,475346.0,484318.5,502150.2,520875.0,517001.3,533928.4,688718.9
4,"""00000""",United States,,SAPCE1,5.0,...,Furnishings and durable household equipment,Millions of current dollars,160490.2,173579.1,...,253938.0,263589.7,276166.5,294219.7,308489.1,322796.3,346025.8,360456.0,411923.1,495001.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1439,"""98000""",Far West,8,SAPCE1,24.0,...,Less: Receipts from sales of goods and serv...,Millions of current dollars,63483.1,66529.7,...,166870.2,171478.0,178397.7,190636.7,200273.2,208327.2,220029.1,234318.9,225108.6,251733.8
1440,Note: See the included footnote file.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1441,SAPCE1: Personal consumption expenditures (PCE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1442,"Last updated: October 6, 2022-- new statistics...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1443,U.S. Bureau of Economic Analysis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
Full_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1444 entries, 0 to 1443
Data columns (total 33 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   GeoFIPS                 1444 non-null   object
 1   GeoName                 1440 non-null   object
 2   Region                  1440 non-null   object
 3   TableName               1440 non-null   object
 4   LineCode                1440 non-null   float64
 5   IndustryClassification  1440 non-null   object
 6   Description             1440 non-null   object
 7   Unit                    1440 non-null   object
 8   1997                    1440 non-null   float64
 9   1998                    1440 non-null   float64
 10  1999                    1440 non-null   float64
 11  2000                    1440 non-null   float64
 12  2001                    1440 non-null   float64
 13  2002                    1440 non-null   float64
 14  2003                    1440 non-null   float64
 15  2004                    1440 non-null   float64
 16  2005                    1440 non-null   float64
 17  2006                    1440 non-null   float64
 18  2007                    1440 non-null   float64
 19  2008                    1440 non-null   float64
 20  2009                    1440 non-null   float64
 21  2010                    1440 non-null   float64
 22  2011                    1440 non-null   float64
 23  2012                    1440 non-null   float64
 24  2013                    1440 non-null   float64
 25  2014                    1440 non-null   float64
 26  2015                    1440 non-null   float64
 27  2016                    1440 non-null   float64
 28  2017                    1440 non-null   float64
 29  2018                    1440 non-null   float64
 30  2019                    1440 non-null   float64
 31  2020                    1440 non-null   float64
 32  2021                    1440 non-null   float64
dtypes: float64(26), object(7)
memory usage: 372.4+ KB

### Cleaning data

In [ ]:
#removing headers / footers
csv = Full_data[Full_data.GeoName.notna()].copy()
assert csv.GeoName.isnull().sum() == 0, 'Test for extra footer information'

In [ ]:
#removing columns we don't need
csv.drop(columns = ['TableName','LineCode', 'IndustryClassification', 'Unit'] , inplace = True)

##Transforming data to match CIM's format.

**Steps:**

Geofips stays the same.

Geoname same.

Region needs to be mapped.

Year column created (categorical) from their respective columns. 

Description Categories made into their own columns.

###Transform Prep

In [ ]:
#state to region map as taken from previous dataset on CIM.
region_map = {'Alabama': 'Southeast',
 'Alaska': 'Far West',
 'Arizona': 'Southwest',
 'Arkansas': 'Southeast',
 'California': 'Far West',
 'Colorado': 'Rocky Mountain',
 'Connecticut': 'New England',
 'Delaware': 'Mideast',
 'District of Columbia': 'Mideast',
 'Far West': 'Far West',
 'Florida': 'Southeast',
 'Georgia': 'Southeast',
 'Great Lakes': 'Great Lakes',
 'Hawaii': 'Far West',
 'Idaho': 'Rocky Mountain',
 'Illinois': 'Great Lakes',
 'Indiana': 'Great Lakes',
 'Iowa': 'Plains',
 'Kansas': 'Plains',
 'Kentucky': 'Southeast',
 'Louisiana': 'Southeast',
 'Maine': 'New England',
 'Maryland': 'Mideast',
 'Massachusetts': 'New England',
 'Michigan': 'Great Lakes',
 'Mideast': 'Mideast',
 'Minnesota': 'Plains',
 'Mississippi': 'Southeast',
 'Missouri': 'Plains',
 'Montana': 'Rocky Mountain',
 'Nebraska': 'Plains',
 'Nevada': 'Far West',
 'New England': 'New England',
 'New Hampshire': 'New England',
 'New Jersey': 'Mideast',
 'New Mexico': 'Southwest',
 'New York': 'Mideast',
 'North Carolina': 'Southeast',
 'North Dakota': 'Plains',
 'Ohio': 'Great Lakes',
 'Oklahoma': 'Southwest',
 'Oregon': 'Far West',
 'Pennsylvania': 'Mideast',
 'Plains': 'Plains',
 'Rhode Island': 'New England',
 'Rocky Mountain': 'Rocky Mountain',
 'South Carolina': 'Southeast',
 'South Dakota': 'Plains',
 'Southeast': 'Southeast',
 'Southwest': 'Southwest',
 'Tennessee': 'Southeast',
 'Texas': 'Southwest',
 'United States': '',
 'Utah': 'Rocky Mountain',
 'Vermont': 'New England',
 'Virginia': 'Southeast',
 'Washington': 'Far West',
 'West Virginia': 'Southeast',
 'Wisconsin': 'Great Lakes',
 'Wyoming': 'Rocky Mountain'}

#### Making Description Categories into their own columns

In [ ]:
Descriptions = csv.Description.unique()
years = list(csv.columns[4:])

#QA
assert len(Descriptions) == 24, 'Looks like the number of descriptions changed. if so, this will affect the columns on the dataset on CIM'
#Visual Sanity Check.
Descriptions, years

(array(['Personal consumption expenditures ', ' Goods ',
        '  Durable goods ', '   Motor vehicles and parts ',
        '   Furnishings and durable household equipment ',
        '   Recreational goods and vehicles ', '   Other durable goods ',
        '  Nondurable goods ',
        '   Food and beverages purchased for off-premises consumption ',
        '   Clothing and footwear ', '   Gasoline and other energy goods ',
        '   Other nondurable goods ', ' Services ',
        '  Household consumption expenditures (for services) ',
        '   Housing and utilities ', '   Health care ',
        '   Transportation services ', '   Recreation services ',
        '   Food services and accommodations ',
        '   Financial services and insurance ', '   Other services ',
        '  Final consumption expenditures of nonprofit institutions serving households (NPISHs) ',
        '   Gross output of nonprofit institutions ',
        '   Less: Receipts from sales of goods and services by nonprofit institutions '],
       dtype=object),
 ['1997',
  '1998',
  '1999',
  '2000',
  '2001',
  '2002',
  '2003',
  '2004',
  '2005',
  '2006',
  '2007',
  '2008',
  '2009',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021'])

In [ ]:
#Creating Geofips to GeoName map
geofips = csv.GeoFIPS.unique()
geoname = csv.GeoName.unique()

geofips_name = {key:value for key,value in zip(geofips, geoname)}

In [ ]:
geofips_name

{' "00000"': 'United States',
 ' "01000"': 'Alabama',
 ' "02000"': 'Alaska',
 ' "04000"': 'Arizona',
 ' "05000"': 'Arkansas',
 ' "06000"': 'California',
 ' "08000"': 'Colorado',
 ' "09000"': 'Connecticut',
 ' "10000"': 'Delaware',
 ' "11000"': 'District of Columbia',
 ' "12000"': 'Florida',
 ' "13000"': 'Georgia',
 ' "15000"': 'Hawaii',
 ' "16000"': 'Idaho',
 ' "17000"': 'Illinois',
 ' "18000"': 'Indiana',
 ' "19000"': 'Iowa',
 ' "20000"': 'Kansas',
 ' "21000"': 'Kentucky',
 ' "22000"': 'Louisiana',
 ' "23000"': 'Maine',
 ' "24000"': 'Maryland',
 ' "25000"': 'Massachusetts',
 ' "26000"': 'Michigan',
 ' "27000"': 'Minnesota',
 ' "28000"': 'Mississippi',
 ' "29000"': 'Missouri',
 ' "30000"': 'Montana',
 ' "31000"': 'Nebraska',
 ' "32000"': 'Nevada',
 ' "33000"': 'New Hampshire',
 ' "34000"': 'New Jersey',
 ' "35000"': 'New Mexico',
 ' "36000"': 'New York',
 ' "37000"': 'North Carolina',
 ' "38000"': 'North Dakota',
 ' "39000"': 'Ohio',
 ' "40000"': 'Oklahoma',
 ' "41000"': 'Oregon',
 ' "42000"': 'Pennsylvania',
 ' "44000"': 'Rhode Island',
 ' "45000"': 'South Carolina',
 ' "46000"': 'South Dakota',
 ' "47000"': 'Tennessee',
 ' "48000"': 'Texas',
 ' "49000"': 'Utah',
 ' "50000"': 'Vermont',
 ' "51000"': 'Virginia',
 ' "53000"': 'Washington',
 ' "54000"': 'West Virginia',
 ' "55000"': 'Wisconsin',
 ' "56000"': 'Wyoming',
 ' "91000"': 'New England',
 ' "92000"': 'Mideast',
 ' "93000"': 'Great Lakes',
 ' "94000"': 'Plains',
 ' "95000"': 'Southeast',
 ' "96000"': 'Southwest',
 ' "97000"': 'Rocky Mountain',
 ' "98000"': 'Far West'}

####Actual Transform

In [ ]:
#Main Transform
final_df = pd.DataFrame()

for year in years:
  csv2 = pd.DataFrame(csv.groupby('GeoFIPS')[year].apply(list)) #list of expenditures in description field ordered in a list by geofips in a given year batch.
  csv2 = csv2[year].apply(pd.Series) #converts to a dataframe columns / #pd.explode should work too

  csv2.columns = Descriptions #new columns previously categorical col 'Descriptions'

  csv2['Year'] = year  #creating cat col for each year of rows
  columns = list(csv2.columns)
  columns.remove('Year')
  columns.insert(0,'Year') #Adding year to front of df
  csv2 = csv2[columns]

  final_df = final_df.append(csv2) # for each year batch append to final df. 

final_df.reset_index(inplace=True)
final_df.sort_values(['GeoFIPS','Year'],inplace = True)
final_df

#for future reference: alternatively, could've also: looped through each group, make group a dataframe with one column, append each group df to a main df, pd.explode the list column, finally change column name.

,GeoFIPS,Year,Personal consumption expenditures,Goods,Durable goods,Motor vehicles and parts,Furnishings and durable household equipment,Recreational goods and vehicles,Other durable goods,Nondurable goods,...,Housing and utilities,Health care,Transportation services,Recreation services,Food services and accommodations,Financial services and insurance,Other services,Final consumption expenditures of nonprofit institutions serving households (NPISHs),Gross output of nonprofit institutions,Less: Receipts from sales of goods and services by nonprofit institutions
0,"""00000""",1997,5536790.1,2006505.5,715529.6,293082.5,160490.2,174632.0,87324.8,1290976.0,...,1009822.3,790947.7,211803.2,208317.0,343427.5,408884.2,451494.8,105588.0,502624.5,397036.5
60,"""00000""",1998,5877248.2,2108439.4,779293.4,320204.7,173579.1,191359.7,94149.8,1329146.0,...,1065472.1,832045.1,225179.9,220204.3,361836.3,446059.4,494205.0,123806.7,542521.1,418714.3
120,"""00000""",1999,6283757.5,2287061.7,855568.3,350730.2,191184.9,210921.5,102731.7,1431493.4,...,1123133.2,863589.3,241343.8,238055.3,380330.7,484587.9,527426.5,138229.0,576318.9,438090.0
180,"""00000""",2000,6767179.3,2453171.8,912571.8,363227.6,208105.7,230858.6,110380.0,1540600.0,...,1198555.7,918424.6,261279.3,254390.0,408781.2,541925.3,572610.9,158040.6,621640.5,463600.0
240,"""00000""",2001,7073801.0,2525593.2,941515.1,383289.5,214940.1,234933.1,108352.4,1584078.0,...,1287493.2,996564.0,259800.4,262290.3,419663.8,529301.7,614011.7,179082.6,676441.5,497358.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1259,"""98000""",2017,2436846.5,702016.0,240791.2,76869.5,55781.0,70790.7,37349.9,461224.8,...,460748.2,400341.9,98842.3,122996.7,180014.1,188514.7,200709.8,82662.8,290990.0,208327.2
1319,"""98000""",2018,2575197.2,738661.8,254360.8,78141.1,60252.4,76791.5,39175.8,484301.0,...,483959.0,422745.3,106858.4,127940.3,191950.8,201373.2,214086.5,87622.0,307651.0,220029.1
1379,"""98000""",2019,2689884.0,763122.6,261400.3,75862.4,62621.5,82678.2,40238.2,501722.3,...,507069.5,449458.4,112290.8,135171.4,204896.0,200929.1,227994.2,88952.0,323270.9,234318.9
1439,"""98000""",2020,2608265.0,796850.7,285829.6,76429.3,70760.8,100814.9,37824.7,511021.1,...,531249.6,427561.7,79290.7,90659.9,161521.4,206986.1,214171.5,99973.4,325082.0,225108.6
1499,"""98000""",2021,2937783.9,933177.8,353120.1,100393.9,83533.7,120173.5,49019.1,580057.8,...,555448.6,468169.8,95185.3,112193.2,211911.3,227877.8,243247.1,90573.0,342306.8,251733.8

In [ ]:
#Mapping GeoName and Region
final_df['GeoName'] = final_df.GeoFIPS.apply(lambda x: geofips_name.get(x))
final_df['Region'] = final_df.GeoName.apply(lambda x: region_map.get(x))

In [ ]:
#reordering columns to CIM's format
columns = list(final_df.columns)
columns.remove('GeoName')
columns.remove('Region')
columns.insert(1,'Region') #Adding year to front of df
columns.insert(1,'GeoName')

final_df = final_df[columns]

In [ ]:
#Sanity Check
final_df

,GeoFIPS,GeoName,Region,Year,Personal consumption expenditures,Goods,Durable goods,Motor vehicles and parts,Furnishings and durable household equipment,Recreational goods and vehicles,...,Housing and utilities,Health care,Transportation services,Recreation services,Food services and accommodations,Financial services and insurance,Other services,Final consumption expenditures of nonprofit institutions serving households (NPISHs),Gross output of nonprofit institutions,Less: Receipts from sales of goods and services by nonprofit institutions
0,"""00000""",United States,,1997,5536790.1,2006505.5,715529.6,293082.5,160490.2,174632.0,...,1009822.3,790947.7,211803.2,208317.0,343427.5,408884.2,451494.8,105588.0,502624.5,397036.5
60,"""00000""",United States,,1998,5877248.2,2108439.4,779293.4,320204.7,173579.1,191359.7,...,1065472.1,832045.1,225179.9,220204.3,361836.3,446059.4,494205.0,123806.7,542521.1,418714.3
120,"""00000""",United States,,1999,6283757.5,2287061.7,855568.3,350730.2,191184.9,210921.5,...,1123133.2,863589.3,241343.8,238055.3,380330.7,484587.9,527426.5,138229.0,576318.9,438090.0
180,"""00000""",United States,,2000,6767179.3,2453171.8,912571.8,363227.6,208105.7,230858.6,...,1198555.7,918424.6,261279.3,254390.0,408781.2,541925.3,572610.9,158040.6,621640.5,463600.0
240,"""00000""",United States,,2001,7073801.0,2525593.2,941515.1,383289.5,214940.1,234933.1,...,1287493.2,996564.0,259800.4,262290.3,419663.8,529301.7,614011.7,179082.6,676441.5,497358.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1259,"""98000""",Far West,Far West,2017,2436846.5,702016.0,240791.2,76869.5,55781.0,70790.7,...,460748.2,400341.9,98842.3,122996.7,180014.1,188514.7,200709.8,82662.8,290990.0,208327.2
1319,"""98000""",Far West,Far West,2018,2575197.2,738661.8,254360.8,78141.1,60252.4,76791.5,...,483959.0,422745.3,106858.4,127940.3,191950.8,201373.2,214086.5,87622.0,307651.0,220029.1
1379,"""98000""",Far West,Far West,2019,2689884.0,763122.6,261400.3,75862.4,62621.5,82678.2,...,507069.5,449458.4,112290.8,135171.4,204896.0,200929.1,227994.2,88952.0,323270.9,234318.9
1439,"""98000""",Far West,Far West,2020,2608265.0,796850.7,285829.6,76429.3,70760.8,100814.9,...,531249.6,427561.7,79290.7,90659.9,161521.4,206986.1,214171.5,99973.4,325082.0,225108.6
1499,"""98000""",Far West,Far West,2021,2937783.9,933177.8,353120.1,100393.9,83533.7,120173.5,...,555448.6,468169.8,95185.3,112193.2,211911.3,227877.8,243247.1,90573.0,342306.8,251733.8

##QA: Run 3 queries for data before and compare with after transform. (automate these if time)

In [ ]:
Descriptions
#Might need to adjust the description names below (space sensitive)

array(['Personal consumption expenditures ', ' Goods ',
       '  Durable goods ', '   Motor vehicles and parts ',
       '   Furnishings and durable household equipment ',
       '   Recreational goods and vehicles ', '   Other durable goods ',
       '  Nondurable goods ',
       '   Food and beverages purchased for off-premises consumption ',
       '   Clothing and footwear ', '   Gasoline and other energy goods ',
       '   Other nondurable goods ', ' Services ',
       '  Household consumption expenditures (for services) ',
       '   Housing and utilities ', '   Health care ',
       '   Transportation services ', '   Recreation services ',
       '   Food services and accommodations ',
       '   Financial services and insurance ', '   Other services ',
       '  Final consumption expenditures of nonprofit institutions serving households (NPISHs) ',
       '   Gross output of nonprofit institutions ',
       '   Less: Receipts from sales of goods and services by nonprofit institutions '],
      dtype=object)

In [ ]:
#Alabama Transportation services = 3829.6 for 2019
assert final_df.query('GeoName == "Alabama" & Year == "2019"')[ '   Transportation services '].values[0] == Full_data.query('GeoName == "Alabama" & Description ==  "   Transportation services "')['2019'].values[0]

#Colorado '   Clothing and footwear' = 7281 for 2019
assert final_df.query('GeoName == "Colorado" & Year == "2019"')[ '   Clothing and footwear '].values[0] == Full_data.query('GeoName == "Colorado" & Description ==  "   Clothing and footwear "')['2019'].values[0]

#United States '   Health care' = 715529.6	 for 1997
assert final_df.query('GeoName == "United States" & Year == "1997"')[ '  Durable goods '].values[0] == Full_data.query('GeoName == "United States" & Description ==  "  Durable goods "')['1997'].values[0]

In [ ]:
#assert all years have 60 counts of data. Every year data should be 60 more than prior year.
#we should have 60 values entered per year. 
final_df.Year.value_counts()

1997    60
2010    60
2020    60
2019    60
2018    60
2017    60
2016    60
2015    60
2014    60
2013    60
2012    60
2011    60
2009    60
1998    60
2008    60
2007    60
2006    60
2005    60
2004    60
2003    60
2002    60
2001    60
2000    60
1999    60
2021    60
Name: Year, dtype: int64

##Exporting data

In [ ]:
#Uncomment when ready to export 
final_df.to_csv('/Updated 'f'{dataset_CIM_name}_for_CIM_'+str(datetime.datetime.now().date()) + '.csv', index = False) #Works only with write access permission to the present drive.
files.download('/Updated ' + f'{dataset_CIM_name}_for_CIM_'+str(datetime.datetime.now().date()) + '.csv')